### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by loppanisoppan** [CEObrainz/Second-Wind#42]
Mod version: 1.9.12
Game version: 1.5.0
DLC version: 3.0

Locations, items and objects doesn't have any text/description.

**Comment by CEObrainz** [comment]
**I can't see any of the new text, what do I do?**
Make sure your language settings in BCML are set according to the version of the game you're using (e.g EU for Europe). Once it's set hit remerge and the issue should be fixed.

**Comment by loppanisoppan** [comment]
@CEObrainz I already had the correct language setting in BCML, still doesn't work.

**Comment by CEObrainz** [comment]
BCML, Cemu and the game need to be set to the same language. A remerge is needed after changing settings in BCML. For further help use Discord.
